# Generated by Django 2.0.5 on 2018-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180715_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='thumbnail',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
