# Generated by Django 2.0.5 on 2018-07-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180715_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
